# Copyright 2026 LanEx Contributors
"""GTKWave handoff helpers: read a VCD's signal list, write a .gtkw save file.

Why this exists: ``gtkwave dump.vcd`` opens with an EMPTY wave pane — GTKWave
never auto-adds signals, the user has to drag every one in from the hierarchy
tree. For a "one click and the waveform is on screen" launch we pre-generate a
GTKWave *save file* (``.gtkw``) that lists the dump's signals, and pass it on
the command line. The save-file format is plain text and version-stable (it is
what GTKWave's own File→Write Save File emits), so no GTKWave-side scripting
(Tcl ``-S``) is needed — Tcl support is a compile-time option some distro/brew
builds lack, while save files always load.

Scope is deliberately narrow and read-only:

* Only the VCD **header** is parsed (everything before ``$enddefinitions``) —
  value-change data is never touched, so a multi-GB dump costs milliseconds.
* FST/GHW dumps are binary — no header parse is attempted; the caller launches
  GTKWave plainly and the user adds signals by hand (GTKWave reads the formats
  natively).
* Any parse trouble degrades to "no signals" — the caller then omits the save
  file rather than failing the launch.

Pure stdlib, no LibreLane APIs, cross-platform.
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Tuple

# Header-read safety caps: a VCD header is normally a few KB. If we haven't hit
# $enddefinitions within these bounds the file is malformed (or not a VCD) —
# stop and report no signals instead of scanning gigabytes of value changes.
_MAX_HEADER_BYTES = 4 * 1024 * 1024
_DEFAULT_SIGNAL_LIMIT = 64


def vcd_signals(vcd_path: str | Path, limit: int = _DEFAULT_SIGNAL_LIMIT) -> List[Tuple[str, int]]:
    """Return ``[(full_dotted_name, bit_width), …]`` from a VCD header.

    * Scope-aware: ``$scope module tb`` … ``$var wire 1 ! clk $end`` yields
      ``tb.clk``.
    * Vector references keep their range: ``$var wire 8 " data [7:0] $end``
      yields ``("tb.data[7:0]", 8)`` — the exact spelling a ``.gtkw`` save file
      needs.
    * Aliases are deduped by identifier code (a VCD may map one id char to many
      names; the first name wins) so the wave pane isn't cluttered with copies.
    * Stops at *limit* signals (huge SoC benches would otherwise produce an
      unusably tall wave pane); never raises — malformed input returns ``[]``.
    """
    p = Path(vcd_path)
    try:
        raw = p.open("rb").read(_MAX_HEADER_BYTES)
    except OSError:
        return []
    text = raw.decode("utf-8", errors="replace")
    head, sep, _ = text.partition("$enddefinitions")
    if not sep:
        return []  # header never ended within the cap — not a (sane) VCD
    scopes: List[str] = []
    seen_ids: set = set()
    out: List[Tuple[str, int]] = []
    tokens = head.split()
    i = 0
    n = len(tokens)
    while i < n and len(out) < max(1, int(limit)):
        tok = tokens[i]
        if tok == "$scope":
            # $scope <type> <name> $end
            name = tokens[i + 2] if i + 2 < n else ""
            if name and name != "$end":
                scopes.append(name)
            while i < n and tokens[i] != "$end":
                i += 1
        elif tok == "$upscope":
            if scopes:
                scopes.pop()
            while i < n and tokens[i] != "$end":
                i += 1
        elif tok == "$var":
            # $var <type> <width> <id> <ref…> $end — ref may be "data [7:0]"
            # (spaced), "data[7:0]", or a plain scalar name.
            j = i + 1
            fields: List[str] = []
            while j < n and tokens[j] != "$end":
                fields.append(tokens[j])
                j += 1
            if len(fields) >= 4:
                width_s, ident = fields[1], fields[2]
                ref = "".join(fields[3:])  # re-join "data [7:0]" → "data[7:0]"
                try:
                    width = max(1, int(width_s))
                except ValueError:
                    width = 1
                if ident not in seen_ids and ref:
                    seen_ids.add(ident)
                    full = ".".join(scopes + [ref]) if scopes else ref
                    out.append((full, width))
            i = j
        i += 1
    return out


def gtkw_text(dump_path: str | Path, signals: List[Tuple[str, int]]) -> str:
    """Render a minimal GTKWave save file preloading *signals*.

    ``@28``/``@22`` are GTKWave trace-flag words (its own generated files use
    the same values): ``@28`` = binary right-justified — right for 1-bit nets;
    ``@22`` = hex right-justified — right for buses. Emitted only when the
    width class changes, exactly like GTKWave's writer."""
    lines = [
        "[*]",
        "[*] GTKWave save file generated by LanEx (preloads the simulation's signals)",
        "[*]",
        f'[dumpfile] "{Path(dump_path).resolve()}"',
        "[timestart] 0",
    ]
    mode = None
    for name, width in signals:
        want = "@28" if width <= 1 else "@22"
        if want != mode:
            lines.append(want)
            mode = want
        lines.append(name)
    return "\n".join(lines) + "\n"


def write_gtkw(save_path: str | Path, dump_path: str | Path,
               signals: List[Tuple[str, int]]) -> str:
    """Write the save file atomically; return its absolute path."""
    from . import platform_env

    sp = Path(save_path)
    platform_env.atomic_write_text(sp, gtkw_text(dump_path, signals))
    return str(sp.resolve())
